ply_file: "/home/lu/4.swarm_mission/SensorSimulator/src/SensorSimulator/realworld.ply"
odom_topic: "/odom"
depth_topic: "/depth_image"
lidar_topic: "/lidar_points"

render_depth: true
depth_fps: 30

render_lidar: true
lidar_fps: 10

expand_x_times: 0      # x方向复制次数（cuda版不使用）
expand_y_times: 0      # y方向复制次数（cuda版不使用）
resolution: 0.1        # 地图分辨率
occupy_threshold: 0    # 大于多少个点才认为占据（cpu版不使用）

camera:
  fx: 80.0             # focal length x
  fy: 80.0             # focal length y
  cx: 80.0             # principal point x (image center)
  cy: 45.0             # principal point y (image center)
  image_width: 160
  image_height: 90
  max_depth_dist: 20.0
  normalize_depth: false

lidar:
  vertical_lines: 16             # 纵向16线
  vertical_angle_start: -15.0    # 起始垂直角度
  vertical_angle_end: 15.0       # 结束垂直角度
  horizontal_num: 360            # 水平360点
  horizontal_resolution: 1.0     # 水平分辨率为1度，horizontal_resolution * horizontal_num = 360
  max_lidar_dist: 20.0
